# secret-example.yaml
apiVersion: v1
kind: Secret

metadata:
  name: app-secret
  namespace: assessment

type: Opaque

stringData:
  MONGO_USERNAME: <your-username>
  MONGO_PASSWORD: <your-password>
  MONGO_URI: mongodb://<username>:<password>@mongodb:27017