apiVersion: v1
kind: Secret

metadata:
  name: app-secret
  namespace: assessment

type: Opaque               #generic key/value Secret.

stringData:
  MONGO_URI: mongodb://admin:password123@mongodb:27017
  MONGO_USERNAME: admin
  MONGO_PASSWORD: password123